language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update --dev
  - composer install --dev

script:
  - mkdir -p build/logs

after_script:
  - php vendor/bin/coveralls
